import { PERMISSIONS_V2 } from "../../src/Constants/permissions.constants.js";

export const rolesList = ["super_admin", "admin", "teacher", "student", "parent"];

export const getRolePermissionCodes = () => ({
  // Super Admin & Admin get all permissions during seeding.
  super_admin: "ALL",
  admin: "ALL",

  teacher: [
    PERMISSIONS_V2.PROFILE.VIEW,
    PERMISSIONS_V2.PROFILE.UPDATE,
    PERMISSIONS_V2.SESSIONS.READ,
    PERMISSIONS_V2.SESSIONS.JOIN,
    PERMISSIONS_V2.SESSIONS.LEAVE,
    PERMISSIONS_V2.HOMEWORK.READ,
    PERMISSIONS_V2.HOMEWORK.CREATE,
    PERMISSIONS_V2.HOMEWORK.UPDATE,
    PERMISSIONS_V2.HOMEWORK.DELETE,
    PERMISSIONS_V2.EXAMS.READ,
    PERMISSIONS_V2.EXAMS.CREATE,
    PERMISSIONS_V2.EXAMS.UPDATE,
    PERMISSIONS_V2.EXAMS.DELETE,
    PERMISSIONS_V2.COURSES.READ,
    PERMISSIONS_V2.SUBJECTS.READ,
    PERMISSIONS_V2.CALENDAR.READ,
    PERMISSIONS_V2.CHAT.READ,
    PERMISSIONS_V2.CHAT.CREATE,
    PERMISSIONS_V2.REQUESTS.CREATE,
    PERMISSIONS_V2.REQUESTS.READ,
    PERMISSIONS_V2.WITHDRAWALS.READ,
    PERMISSIONS_V2.WITHDRAWALS.CREATE,
    PERMISSIONS_V2.FINANCES.READ,
  ],

  student: [
    PERMISSIONS_V2.PROFILE.VIEW,
    PERMISSIONS_V2.PROFILE.UPDATE,
    PERMISSIONS_V2.SESSIONS.READ,
    PERMISSIONS_V2.SESSIONS.JOIN,
    PERMISSIONS_V2.SESSIONS.LEAVE,
    PERMISSIONS_V2.HOMEWORK.READ,
    PERMISSIONS_V2.EXAMS.READ,
    PERMISSIONS_V2.COURSES.READ,
    PERMISSIONS_V2.CALENDAR.READ,
    PERMISSIONS_V2.CHAT.READ,
    PERMISSIONS_V2.CHAT.CREATE,
    PERMISSIONS_V2.REQUESTS.CREATE,
    PERMISSIONS_V2.REQUESTS.READ,
  ],

  parent: [
    PERMISSIONS_V2.PROFILE.VIEW,
    PERMISSIONS_V2.PROFILE.UPDATE,
    PERMISSIONS_V2.SESSIONS.READ,
    PERMISSIONS_V2.HOMEWORK.READ,
    PERMISSIONS_V2.EXAMS.READ,
    PERMISSIONS_V2.CALENDAR.READ,
  ],
});
