import { PERMISSIONS_V2 } from "../../src/Constants/permissions.constants.js";

export const rolesList = ["super_admin", "admin", "teacher", "student", "parent", "moderator"];

const allPermissionsList = Object.values(PERMISSIONS_V2).flatMap((group) =>
  Object.values(group),
);

const excludedForModerator = new Set([
  ...Object.values(PERMISSIONS_V2.DASHBOARD || {}),
  ...Object.values(PERMISSIONS_V2.SETTINGS || {}),
  ...Object.values(PERMISSIONS_V2.ROLES || {}),
  ...Object.values(PERMISSIONS_V2.PERMISSIONS || {}),
  ...Object.values(PERMISSIONS_V2.POLICIES || {}),
  ...Object.values(PERMISSIONS_V2.FINANCES || {}),
  ...Object.values(PERMISSIONS_V2.WITHDRAWALS || {}),
]);

export const getRolePermissionCodes = () => ({
  // Super Admin & Admin get all permissions during seeding.
  super_admin: "ALL",
  admin: "ALL",

  moderator: allPermissionsList.filter(
    (code) => !excludedForModerator.has(code),
  ),

  teacher: [
    PERMISSIONS_V2.PROFILE.VIEW,
    PERMISSIONS_V2.PROFILE.UPDATE,
    PERMISSIONS_V2.SESSIONS.READ,
    PERMISSIONS_V2.SESSIONS.JOIN,
    PERMISSIONS_V2.SESSIONS.LEAVE,
    PERMISSIONS_V2.SESSIONS.READ_USER_SCHEDULES,
    PERMISSIONS_V2.HOMEWORK.READ,
    PERMISSIONS_V2.HOMEWORK.CREATE,
    PERMISSIONS_V2.HOMEWORK.UPDATE,
    PERMISSIONS_V2.HOMEWORK.DELETE,
    PERMISSIONS_V2.HOMEWORK.READ_STUDENT_HOMEWORK,
    PERMISSIONS_V2.EXAMS.READ,
    PERMISSIONS_V2.EXAMS.CREATE,
    PERMISSIONS_V2.EXAMS.UPDATE,
    PERMISSIONS_V2.EXAMS.DELETE,
    PERMISSIONS_V2.EXAMS.READ_STUDENT_EXAMS,
    PERMISSIONS_V2.COURSES.READ,
    PERMISSIONS_V2.SUBJECTS.READ,
    PERMISSIONS_V2.CALENDAR.READ,
    PERMISSIONS_V2.CHAT.READ,
    PERMISSIONS_V2.CHAT.CREATE,
    PERMISSIONS_V2.REQUESTS.CREATE,
    PERMISSIONS_V2.REQUESTS.READ,
    PERMISSIONS_V2.WITHDRAWALS.READ,
    PERMISSIONS_V2.WITHDRAWALS.CREATE,
    PERMISSIONS_V2.WITHDRAWALS.READ_MY_WITHDRAWALS,
    PERMISSIONS_V2.FINANCES.READ,
    PERMISSIONS_V2.FINANCES.READ_MY_TRANSACTIONS,
    PERMISSIONS_V2.TEACHERS.READ_MY_STUDENTS,
    PERMISSIONS_V2.DAILY_QURAN_RECITATION.READ,
    PERMISSIONS_V2.DAILY_QURAN_RECITATION.CREATE,
    PERMISSIONS_V2.DAILY_QURAN_RECITATION.UPDATE,
    PERMISSIONS_V2.DAILY_QURAN_RECITATION.DELETE,
    PERMISSIONS_V2.DAILY_QURAN_RECITATION.READ_TEACHER_RECITATIONS,
    PERMISSIONS_V2.VIOLATIONS.READ_MY_VIOLATIONS,
  ],

  student: [
    PERMISSIONS_V2.PROFILE.VIEW,
    PERMISSIONS_V2.PROFILE.UPDATE,
    PERMISSIONS_V2.SESSIONS.READ,
    PERMISSIONS_V2.SESSIONS.JOIN,
    PERMISSIONS_V2.SESSIONS.LEAVE,
    PERMISSIONS_V2.SESSIONS.READ_USER_SCHEDULES,
    PERMISSIONS_V2.HOMEWORK.READ,
    PERMISSIONS_V2.HOMEWORK.READ_STUDENT_HOMEWORK,
    PERMISSIONS_V2.EXAMS.READ,
    PERMISSIONS_V2.EXAMS.READ_STUDENT_EXAMS,
    PERMISSIONS_V2.COURSES.READ,
    PERMISSIONS_V2.CALENDAR.READ,
    PERMISSIONS_V2.CHAT.READ,
    PERMISSIONS_V2.CHAT.CREATE,
    PERMISSIONS_V2.REQUESTS.CREATE,
    PERMISSIONS_V2.REQUESTS.READ,
    PERMISSIONS_V2.DAILY_QURAN_RECITATION.READ,
    PERMISSIONS_V2.DAILY_QURAN_RECITATION.UPDATE,
    PERMISSIONS_V2.DAILY_QURAN_RECITATION.READ_MY_RECITATIONS,
  ],

  parent: [
    PERMISSIONS_V2.PROFILE.VIEW,
    PERMISSIONS_V2.PROFILE.UPDATE,
    PERMISSIONS_V2.SESSIONS.READ,
    PERMISSIONS_V2.HOMEWORK.READ,
    PERMISSIONS_V2.EXAMS.READ,
    PERMISSIONS_V2.CALENDAR.READ,
    PERMISSIONS_V2.DAILY_QURAN_RECITATION.READ,
    PERMISSIONS_V2.DAILY_QURAN_RECITATION.READ_MY_RECITATIONS,
  ],
});
